// Mood configuration — maps weather conditions to visual parameters
// Each mood drives: sky color, fog, particle counts, post-processing, and UI theming

const moods = {
  thunderstorm: {
    name: 'thunderstorm',
    label: 'Thunderstorm',
    emoji: '⛈️',
    skyColor: '#0a0a14',
    fogColor: '#1a1a2e',
    fogNear: 10,
    fogFar: 80,
    ambientIntensity: 0.08,
    ambientColor: '#2d1b69',
    particles: { count: 15000, speed: 1.8, size: 0.015, opacity: 0.5 },
    lightning: { enabled: true, minInterval: 1.5, maxInterval: 5, intensity: 8 },
    wind: { strength: 0.4, turbulence: 0.3 },
    bloom: { intensity: 1.2, luminanceThreshold: 0.1 },
    vignette: { darkness: 0.8, offset: 0.3 },
    chromaticAberration: { offset: 0.003 },
    overlay: {
      gradient: 'radial-gradient(ellipse at 50% 30%, rgba(45,27,105,0.3) 0%, rgba(10,10,20,0.7) 100%)',
      blend: 'multiply',
    },
    uiAccent: '#7c5cbf',
    uiGlow: 'rgba(124,92,191,0.4)',
    textColor: '#e2d8f5',
  },

  rain: {
    name: 'rain',
    label: 'Rainy',
    emoji: '🌧️',
    skyColor: '#1a2332',
    fogColor: '#2c3e50',
    fogNear: 20,
    fogFar: 120,
    ambientIntensity: 0.15,
    ambientColor: '#4a6fa5',
    particles: { count: 8000, speed: 1.2, size: 0.012, opacity: 0.4 },
    lightning: { enabled: false },
    wind: { strength: 0.15, turbulence: 0.1 },
    bloom: { intensity: 0.4, luminanceThreshold: 0.6 },
    vignette: { darkness: 0.6, offset: 0.4 },
    chromaticAberration: { offset: 0 },
    overlay: {
      gradient: 'linear-gradient(180deg, rgba(26,35,50,0.4) 0%, rgba(44,62,80,0.5) 100%)',
      blend: 'multiply',
    },
    uiAccent: '#4a90d9',
    uiGlow: 'rgba(74,144,217,0.3)',
    textColor: '#c8ddf0',
  },

  drizzle: {
    name: 'drizzle',
    label: 'Drizzle',
    emoji: '🌦️',
    skyColor: '#2c3e50',
    fogColor: '#3d5a80',
    fogNear: 30,
    fogFar: 150,
    ambientIntensity: 0.2,
    ambientColor: '#5a8dad',
    particles: { count: 4000, speed: 0.7, size: 0.008, opacity: 0.3 },
    lightning: { enabled: false },
    wind: { strength: 0.08, turbulence: 0.05 },
    bloom: { intensity: 0.3, luminanceThreshold: 0.7 },
    vignette: { darkness: 0.4, offset: 0.5 },
    chromaticAberration: { offset: 0 },
    overlay: {
      gradient: 'linear-gradient(180deg, rgba(44,62,80,0.3) 0%, rgba(61,90,128,0.3) 100%)',
      blend: 'multiply',
    },
    uiAccent: '#5a9fd4',
    uiGlow: 'rgba(90,159,212,0.3)',
    textColor: '#d0e4f0',
  },

  snow: {
    name: 'snow',
    label: 'Snowy',
    emoji: '❄️',
    skyColor: '#1a2233',
    fogColor: '#2a3a4e',
    fogNear: 15,
    fogFar: 100,
    ambientIntensity: 0.25,
    ambientColor: '#8eafc2',
    particles: { count: 3000, speed: 0.25, size: 0.04, opacity: 0.7 },
    lightning: { enabled: false },
    wind: { strength: 0.06, turbulence: 0.08 },
    bloom: { intensity: 0.6, luminanceThreshold: 0.5 },
    vignette: { darkness: 0.35, offset: 0.5 },
    chromaticAberration: { offset: 0 },
    overlay: {
      gradient: 'radial-gradient(ellipse at 50% 50%, rgba(142,175,194,0.15) 0%, rgba(26,34,51,0.4) 100%)',
      blend: 'screen',
    },
    uiAccent: '#7eb8d8',
    uiGlow: 'rgba(126,184,216,0.3)',
    textColor: '#d8eaf5',
  },

  clear: {
    name: 'clear',
    label: 'Clear Sky',
    emoji: '☀️',
    skyColor: '#0c1445',
    fogColor: '#1a2a55',
    fogNear: 50,
    fogFar: 300,
    ambientIntensity: 0.35,
    ambientColor: '#ffd475',
    particles: { count: 0, speed: 0, size: 0, opacity: 0 },
    lightning: { enabled: false },
    wind: { strength: 0.02, turbulence: 0.01 },
    bloom: { intensity: 0.8, luminanceThreshold: 0.4 },
    vignette: { darkness: 0.3, offset: 0.6 },
    chromaticAberration: { offset: 0 },
    overlay: {
      gradient: 'radial-gradient(ellipse at 50% 20%, rgba(255,212,117,0.15) 0%, rgba(12,20,69,0.3) 100%)',
      blend: 'screen',
    },
    uiAccent: '#f0a830',
    uiGlow: 'rgba(240,168,48,0.3)',
    textColor: '#ffedc8',
  },

  clouds: {
    name: 'clouds',
    label: 'Cloudy',
    emoji: '☁️',
    skyColor: '#1c2333',
    fogColor: '#3a4556',
    fogNear: 15,
    fogFar: 90,
    ambientIntensity: 0.18,
    ambientColor: '#7a8a9e',
    particles: { count: 0, speed: 0, size: 0, opacity: 0 },
    lightning: { enabled: false },
    wind: { strength: 0.1, turbulence: 0.05 },
    bloom: { intensity: 0.3, luminanceThreshold: 0.65 },
    vignette: { darkness: 0.5, offset: 0.4 },
    chromaticAberration: { offset: 0 },
    overlay: {
      gradient: 'linear-gradient(180deg, rgba(28,35,51,0.3) 0%, rgba(58,69,86,0.4) 100%)',
      blend: 'multiply',
    },
    uiAccent: '#8899aa',
    uiGlow: 'rgba(136,153,170,0.3)',
    textColor: '#c8d0dd',
  },

  mist: {
    name: 'mist',
    label: 'Misty',
    emoji: '🌫️',
    skyColor: '#1a2a2a',
    fogColor: '#2a3a3a',
    fogNear: 5,
    fogFar: 40,
    ambientIntensity: 0.12,
    ambientColor: '#5a7a6a',
    particles: { count: 2000, speed: 0.05, size: 0.08, opacity: 0.15 },
    lightning: { enabled: false },
    wind: { strength: 0.03, turbulence: 0.02 },
    bloom: { intensity: 0.5, luminanceThreshold: 0.5 },
    vignette: { darkness: 0.7, offset: 0.3 },
    chromaticAberration: { offset: 0 },
    overlay: {
      gradient: 'radial-gradient(ellipse at 50% 50%, rgba(90,122,106,0.2) 0%, rgba(26,42,42,0.6) 100%)',
      blend: 'multiply',
    },
    uiAccent: '#6a9a8a',
    uiGlow: 'rgba(106,154,138,0.3)',
    textColor: '#c0ddd0',
  },

  default: {
    name: 'default',
    label: 'Loading',
    emoji: '🌌',
    skyColor: '#0a0a1a',
    fogColor: '#0f0f2a',
    fogNear: 50,
    fogFar: 500,
    ambientIntensity: 0.1,
    ambientColor: '#4a4a8a',
    particles: { count: 0, speed: 0, size: 0, opacity: 0 },
    lightning: { enabled: false },
    wind: { strength: 0, turbulence: 0 },
    bloom: { intensity: 0.5, luminanceThreshold: 0.5 },
    vignette: { darkness: 0.5, offset: 0.5 },
    chromaticAberration: { offset: 0 },
    overlay: {
      gradient: 'radial-gradient(ellipse at 50% 50%, rgba(74,74,138,0.1) 0%, rgba(10,10,26,0.5) 100%)',
      blend: 'normal',
    },
    uiAccent: '#6a6aaa',
    uiGlow: 'rgba(106,106,170,0.3)',
    textColor: '#c0c0e0',
  },
};

// Map OpenWeatherMap condition strings to mood keys
const conditionMap = {
  Thunderstorm: 'thunderstorm',
  Rain: 'rain',
  Drizzle: 'drizzle',
  Snow: 'snow',
  Clear: 'clear',
  Clouds: 'clouds',
  Mist: 'mist',
  Haze: 'mist',
  Fog: 'mist',
  Smoke: 'mist',
  Dust: 'mist',
  Sand: 'mist',
  Ash: 'mist',
  Squall: 'thunderstorm',
  Tornado: 'thunderstorm',
};

export function getMoodFromCondition(condition) {
  const key = conditionMap[condition] || 'default';
  return moods[key];
}

export default moods;
